package es.runtime.linker;

import java.util.Objects;

/**
 * Represents a an adapter for invoking superclass methods on an adapter instance generated by {@code JavaAdapterBytecodeGenerator}.
 *
 * Note that objects of this class are just wrappers around the adapter instances, without any behavior.
 * All the behavior is defined in the {@code JavaSuperAdapterLinker}.
 */
class JavaSuperAdapter {

  private final Object adapter;

  JavaSuperAdapter(Object adapter) {
    this.adapter = Objects.requireNonNull(adapter);
  }

  public Object getAdapter() {
    return adapter;
  }

}
